package com.eirs.fcm.repository.entity;

public interface SystemConfigKeys {

    String ORGANISATION_ID = "ORGANISATION_ID";
    String FCM_NO_OF_OPERATORS = "NO_OF_OPERATORS";
    String FCM_OPERATOR = "OPERATORS_<NUMBER>";
    String SHORT_CODE = "<OPERATOR>_SHORT_CODE";
    String SOURCE_SERVER = "SOURCE_SERVER";
    String DEST_DAILY_FILE_PATH = "<OPERATOR>_DEST_FILEPATH_DAILY_";

    String DEST_WEEKLY_FILE_PATH = "<OPERATOR>_DEST_FILEPATH_WEEKLY_";
    String DEST_SERVER = "<OPERATOR>_DEST_SERVER_";

    String NO_OF_DEST = "<OPERATOR>_NO_OF_DEST";
    String SFTP_URL = "<OPERATOR>_COPY_URL";

    String ENABLE_BLACKED_LIST_FULL_FILE = "ENABLE_BLACKED_LIST_FULL_FILE";

    String ENABLE_BLOCKED_TAC_FULL_FILE = "ENABLE_BLOCKED_TAC_FULL_FILE";

    String ENABLE_ALLOWED_TAC_FULL_FILE = "ENABLE_ALLOWED_TAC_FULL_FILE";

    String ENABLE_TRACKED_LIST_FULL_FILE = "ENABLE_TRACKED_LIST_FULL_FILE";

    String ENABLE_EXCEPTION_LIST_FULL_FILE = "ENABLE_EXCEPTION_LIST_FULL_FILE";

    String ENABLE_BLACKED_LIST_INCREMENT_FILE = "ENABLE_BLACKED_LIST_INCREMENT_FILE";

    String ENABLE_BLOCKED_TAC_INCREMENT_FILE = "ENABLE_BLOCKED_TAC_INCREMENT_FILE";

    String ENABLE_ALLOWED_TAC_INCREMENT_FILE = "ENABLE_ALLOWED_TAC_INCREMENT_FILE";

    String ENABLE_TRACKED_LIST_INCREMENT_FILE = "ENABLE_TRACKED_LIST_INCREMENT_FILE";

    String ENABLE_EXCEPTION_LIST_INCREMENT_FILE = "ENABLE_EXCEPTION_LIST_INCREMENT_FILE";

}
