spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app
    username: root
    password: ENC(jxNzi7e8T94AnHUxgizmuQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: false
scheduler:
  daily:
    enable: false
    cronjob: "0 * * * * *"
    # SECOND, MIN , HOUR , DAY(Month) , Month , DAY (Week) 1-Monday and 7-Sunday
  weekly:
    enable: false
    cronjob: "0 0 1 * * 1"
#    cronjob: "30 * * * * *"


files:
  path: D:/Files

alerts:
  postUrl: http://127.0.0.1:9504/eir/alert
  processId: FileCreation
  alerts-mapping:
    FILE_CREATION_ERROR:
      alertId: ALERT2121
      message: "Not able to call CORE Module, <URL> : <EXCEPTION>."
    FILE_COPY_URL_EXCEPTION:
      alertId: ALERT2121
      message: "Not able to call CORE Module, <URL> : <EXCEPTION>."
    DATABASE_EXCEPTION:
      alertId: ALERT2020
      message: "Database Exception, <LIST> : <EXCEPTION>."
    CONFIGURATION_VALUE_MISSING:
      alertId: ALERT2020
      message: "Missing value for Key: <CONFIG_KEY>."
    CONFIGURATION_VALUE_WRONG:
      alertId: ALERT2020
      message: "Wrong value for Key: <CONFIG_KEY> ConfiguredValue: <CONFIG_VALUE>"
sftp:
  copy-url:
    retry-time-in-min: 10
jasypt:
  encryptor:
    password: eir
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator