package com.eirs.fcm.constants;

public enum AlertIds {

    CONFIGURATION_VALUE_MISSING, CONFIGURATION_VALUE_WRONG,
    FILE_CREATION_ERROR,MODULE_EXECUTED_WITH_EXCEPTION,
    FILE_COPY_URL_EXCEPTION, DATABASE_EXCEPTION,
}
